In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("repoDB.csv")
data

,Unnamed: 0,name,url,description,stars,created_at,language,forks,watchers,open_issues,owner,contributors_count,contributors,contributions_count
0,0,learn-javascript,https://github.com/sumn2u/learn-javascript,A book that teaches JavaScript,635,2023-01-01 15:16:26+00:00,HTML,32,635,1,sumn2u,6,"[""'gnwx'"", "" 'sumn2u'"", "" 'Anuj-Khadka'"", "" 's...","[83, 64, 2, 2, 1, 1]"
1,1,LinksHub,https://github.com/rupali-codes/LinksHub,LinksHub aims to provide developers with acces...,359,2023-01-01 18:55:44+00:00,TypeScript,305,359,99,rupali-codes,30,"[""'rupali-codes'"", "" 'CBID2'"", "" 'Anmol-Baranw...","[76, 65, 57, 47, 26, 17, 17, 14, 13, 11, 9, 9,..."
2,2,90DaysOfDevOps,https://github.com/LondheShubham153/90DaysOfDe...,This repository is a Challenge for the DevOps ...,352,2023-01-01 11:41:21+00:00,Python,2274,352,54,LondheShubham153,16,"[""'LondheShubham153'"", "" 'RishikeshOps'"", "" 's...","[167, 24, 13, 10, 10, 5, 5, 3, 2, 1, 1, 1, 1, ..."
3,3,Obsidian-Tasks-Timeline,https://github.com/702573N/Obsidian-Tasks-Time...,A custom view build with Obsidian-Dataview to ...,174,2023-01-01 22:02:50+00:00,JavaScript,14,174,18,702573N,2,"[""'702573N'"", "" 'dranidis'""]","[108, 2]"
4,4,scribepod,https://github.com/yacineMTB/scribepod,Some of the scripts I use for scribepod @ http...,150,2023-01-01 00:34:43+00:00,Jupyter Notebook,15,150,0,yacineMTB,1,"[""'yacineMTB'""]",[22]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15485,15485,IAT-Tracer,https://github.com/YoavLevi/IAT-Tracer,An automation plugin for Tiny-Tracer framework...,23,2023-06-30 13:05:33+00:00,Python,2,23,0,YoavLevi,1,"[""'YoavLevi'""]",[17]
15486,15486,lens-algorithm-playground,https://github.com/dabit3/lens-algorithm-playg...,This app showcases various Lens recommendation...,22,2023-06-30 00:10:22+00:00,TypeScript,1,22,0,dabit3,2,"[""'dabit3'"", "" 'YosephKS'""]","[12, 9]"
15487,15487,Egyscan,https://github.com/dragonked2/Egyscan,Egyscan is more than just a web vulnerability ...,21,2023-06-30 21:40:47+00:00,Python,7,21,0,dragonked2,1,"[""'dragonked2'""]",[38]
15488,15488,TamaDroppy,https://github.com/CNCKitchen/TamaDroppy,Digital Egg Drop Egg,20,2023-06-30 19:05:42+00:00,C++,2,20,0,CNCKitchen,1,"[""'CNCKitchen'""]",[2]
15489,15489,Hacking-Animation,https://github.com/PB2204/Hacking-Animation,This Is Very Beautiful Interface For Hackers ....,18,2023-06-30 05:17:18+00:00,JavaScript,0,18,0,PB2204,1,"[""'PB2204'""]",[1]

In [3]:
import pyodbc

In [4]:
# Connexion Ã  la base de donnÃ©es SQL Server
conn = pyodbc.connect("Driver={SQL Server};Server=LAPTOP-IGO4LBSV\SQLEXPRESS;Database=github_db;Trusted_Connection=yes;")
cursor = conn.cursor()

cursor.execute("SELECT @@version;")
row = cursor.fetchone()
while row: 
    print(row[0])
    row = cursor.fetchone()

Microsoft SQL Server 2022 (RTM) - 16.0.1000.6 (X64)
	Oct  8 2022 05:58:25
	Copyright (C) 2022 Microsoft Corporation
	Express Edition (64-bit) on Windows 10 Pro 10.0 <X64> (Build 19045: )

In [5]:
# Insertion des donnÃ©es dans la table "Owner"
owner_table = data[["owner"]].drop_duplicates().reset_index(drop=True)

owner_table.insert(0, "id_owner", range(1, len(owner_table) + 1))
#insert_owner_data("Owner", owner_table[["id_owner", "owner"]])
display(owner_table)

       id_owner             owner
0             1            sumn2u
1             2      rupali-codes
2             3  LondheShubham153
3             4           702573N
4             5         yacineMTB
...         ...               ...
12059     12060        increments
12060     12061          Hacksore
12061     12062          YoavLevi
12062     12063        dragonked2
12063     12064        CNCKitchen

[12064 rows x 2 columns]

In [ ]:
# Insertion des donnÃ©es de la table "Owner" dans la base de donnees

def insert_owner_data(cursor, owner_data):
    for index, row in owner_data.iterrows():
        cursor.execute("INSERT INTO Owners (id_owner, name_o) VALUES (?, ?)", row["id_owner"], row["owner"])
    conn.commit()

    # Appel de la fonction pour insÃ©rer les donnÃ©es dans la table "Owner"
insert_owner_data(cursor, owner_table)

# Fermeture de la connexion Ã  la base de donnÃ©es
conn.close()

In [12]:
# CrÃ©ation de la table language_table (id_langage sera gÃ©nÃ©rÃ© automatiquement)
language_table = data[["language"]].drop_duplicates().reset_index(drop=True)
language_table.insert(0, "id_langage", range(1, len(language_table) + 1))
display(language_table)

     id_langage  language
0             1         1
1             2         2
2             3         3
3             4         4
4             5         5
..          ...       ...
144         145       145
145         146       146
146         147       147
147         148       148
148         149       149

[149 rows x 2 columns]

In [7]:
#la relation entre langage et repo
for index,L in language_table.iterrows():
    data['language'].replace(L['language'],L['id_langage'],inplace=True)

In [8]:
# la relation entre owner et repo
for index,O in owner_table.iterrows():
    data['owner'].replace(O['owner'],O['id_owner'],inplace=True)

In [9]:
# CrÃ©ation de la table repo_table (id_repo sera gÃ©nÃ©rÃ© automatiquement)
repo_table = data[["name", "url", "description", "stars", "created_at", "forks", "watchers", "open_issues", "contributors_count", "language", "owner"]].reset_index(drop=True)
repo_table.insert(0, "id_repo", range(1, len(repo_table) + 1))

In [10]:
data

,Unnamed: 0,name,url,description,stars,created_at,language,forks,watchers,open_issues,owner,contributors_count,contributors,contributions_count
0,0,learn-javascript,https://github.com/sumn2u/learn-javascript,A book that teaches JavaScript,635,2023-01-01 15:16:26+00:00,1,32,635,1,1,6,"[""'gnwx'"", "" 'sumn2u'"", "" 'Anuj-Khadka'"", "" 's...","[83, 64, 2, 2, 1, 1]"
1,1,LinksHub,https://github.com/rupali-codes/LinksHub,LinksHub aims to provide developers with acces...,359,2023-01-01 18:55:44+00:00,2,305,359,99,2,30,"[""'rupali-codes'"", "" 'CBID2'"", "" 'Anmol-Baranw...","[76, 65, 57, 47, 26, 17, 17, 14, 13, 11, 9, 9,..."
2,2,90DaysOfDevOps,https://github.com/LondheShubham153/90DaysOfDe...,This repository is a Challenge for the DevOps ...,352,2023-01-01 11:41:21+00:00,3,2274,352,54,3,16,"[""'LondheShubham153'"", "" 'RishikeshOps'"", "" 's...","[167, 24, 13, 10, 10, 5, 5, 3, 2, 1, 1, 1, 1, ..."
3,3,Obsidian-Tasks-Timeline,https://github.com/702573N/Obsidian-Tasks-Time...,A custom view build with Obsidian-Dataview to ...,174,2023-01-01 22:02:50+00:00,4,14,174,18,4,2,"[""'702573N'"", "" 'dranidis'""]","[108, 2]"
4,4,scribepod,https://github.com/yacineMTB/scribepod,Some of the scripts I use for scribepod @ http...,150,2023-01-01 00:34:43+00:00,5,15,150,0,5,1,"[""'yacineMTB'""]",[22]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15485,15485,IAT-Tracer,https://github.com/YoavLevi/IAT-Tracer,An automation plugin for Tiny-Tracer framework...,23,2023-06-30 13:05:33+00:00,3,2,23,0,12062,1,"[""'YoavLevi'""]",[17]
15486,15486,lens-algorithm-playground,https://github.com/dabit3/lens-algorithm-playg...,This app showcases various Lens recommendation...,22,2023-06-30 00:10:22+00:00,2,1,22,0,1432,2,"[""'dabit3'"", "" 'YosephKS'""]","[12, 9]"
15487,15487,Egyscan,https://github.com/dragonked2/Egyscan,Egyscan is more than just a web vulnerability ...,21,2023-06-30 21:40:47+00:00,3,7,21,0,12063,1,"[""'dragonked2'""]",[38]
15488,15488,TamaDroppy,https://github.com/CNCKitchen/TamaDroppy,Digital Egg Drop Egg,20,2023-06-30 19:05:42+00:00,17,2,20,0,12064,1,"[""'CNCKitchen'""]",[2]
15489,15489,Hacking-Animation,https://github.com/PB2204/Hacking-Animation,This Is Very Beautiful Interface For Hackers ....,18,2023-06-30 05:17:18+00:00,4,0,18,0,10323,1,"[""'PB2204'""]",[1]

In [11]:
repo_table

,id_repo,name,url,description,stars,created_at,forks,watchers,open_issues,contributors_count,language,owner
0,1,learn-javascript,https://github.com/sumn2u/learn-javascript,A book that teaches JavaScript,635,2023-01-01 15:16:26+00:00,32,635,1,6,1,1
1,2,LinksHub,https://github.com/rupali-codes/LinksHub,LinksHub aims to provide developers with acces...,359,2023-01-01 18:55:44+00:00,305,359,99,30,2,2
2,3,90DaysOfDevOps,https://github.com/LondheShubham153/90DaysOfDe...,This repository is a Challenge for the DevOps ...,352,2023-01-01 11:41:21+00:00,2274,352,54,16,3,3
3,4,Obsidian-Tasks-Timeline,https://github.com/702573N/Obsidian-Tasks-Time...,A custom view build with Obsidian-Dataview to ...,174,2023-01-01 22:02:50+00:00,14,174,18,2,4,4
4,5,scribepod,https://github.com/yacineMTB/scribepod,Some of the scripts I use for scribepod @ http...,150,2023-01-01 00:34:43+00:00,15,150,0,1,5,5
...,...,...,...,...,...,...,...,...,...,...,...,...
15485,15486,IAT-Tracer,https://github.com/YoavLevi/IAT-Tracer,An automation plugin for Tiny-Tracer framework...,23,2023-06-30 13:05:33+00:00,2,23,0,1,3,12062
15486,15487,lens-algorithm-playground,https://github.com/dabit3/lens-algorithm-playg...,This app showcases various Lens recommendation...,22,2023-06-30 00:10:22+00:00,1,22,0,2,2,1432
15487,15488,Egyscan,https://github.com/dragonked2/Egyscan,Egyscan is more than just a web vulnerability ...,21,2023-06-30 21:40:47+00:00,7,21,0,1,3,12063
15488,15489,TamaDroppy,https://github.com/CNCKitchen/TamaDroppy,Digital Egg Drop Egg,20,2023-06-30 19:05:42+00:00,2,20,0,1,17,12064
15489,15490,Hacking-Animation,https://github.com/PB2204/Hacking-Animation,This Is Very Beautiful Interface For Hackers ....,18,2023-06-30 05:17:18+00:00,0,18,0,1,4,10323

In [36]:
# Insertion des donnÃ©es dans la table "Repo"
def insert_langage_data(cursor, repo_data):
    for index, row in repo_data.iterrows():
        cursor.execute("INSERT INTO Repo (id_repo, name_repo, url, description, stars, created_at, forks, watchers, open_issues, contributors_count, id_langage, id_owner) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", row["id_repo"], row["name"], row["url"], row["description"], row["stars"], row["created_at"], row["forks"], row["watchers"], row["open_issues"], row["contributors_count"], row["language"], row["owner"])
    conn.commit()

# Appel de la fonction pour insÃ©rer les donnÃ©es dans la table "Repo"
insert_langage_data(cursor, repo_table)

# Fermeture de la connexion Ã  la base de donnÃ©es
conn.close()

In [24]:
# Insertion des donnÃ©es dans la table "Langage"
def insert_langage_data(cursor, langage_data):
    for index, row in langage_data.iterrows():
        cursor.execute("INSERT INTO Langage (id_langage, langage) VALUES (?, ?)", row["id_langage"], row["language"])
    conn.commit()

# Appel de la fonction pour insÃ©rer les donnÃ©es dans la table "Langage"
insert_langage_data(cursor, language_table)

# Fermeture de la connexion Ã  la base de donnÃ©es
conn.close()

In [ ]:
# CrÃ©ation de la table language_table (id_langage sera gÃ©nÃ©rÃ© automatiquement)
Contributors_table = data[["contributors"]].drop_duplicates().reset_index(drop=True)
Contributors_table.insert(0, "id_contributors", range(1, len(Contributors_table) + 1))
display(Contributors_table)

In [13]:
data1 = data[['url', 'contributors', 'contributions_count']]
data1 = data1.sort_values(by="url")
repos1 = repo_table[['id_repo', 'url']]
repos1 = repos1.sort_values(by="url")
repos1 = repos1.drop_duplicates()

In [14]:
data1['id_repo'] = repos1['id_repo']
data1 = data1.explode('contributors')

In [15]:
contributions = data[['url', 'contributors']]
contributions['contributors'].astype(str)
# split the contributors column
contributions['contributors'] = contributions['contributors'].astype(str).str.split(',')
# explode the contributors column
contributions = contributions.explode('contributors')
# remove the spaces
contributions['contributors'] = contributions['contributors'].str.strip()
# remove the quotes
contributions['contributors'] = contributions['contributors'].str.replace("'", "")

contributions1 = data[['url', 'contributions_count']]
# split the contributions_count column
contributions1['contributions_count'] = contributions1['contributions_count'].astype(str).str.split(',')
# explode the contributions_count column
contributions1 = contributions1.explode('contributions_count')
# remove the spaces
contributions1['contributions_count'] = contributions1['contributions_count'].str.strip()
# explode the contributions_count column
contributions1 = contributions1.explode('contributions_count')

contributions["contributions_count"]  = contributions1["contributions_count"]

C:\Users\Youcode\AppData\Local\Temp\ipykernel_31736\3053713290.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  contributions['contributors'] = contributions['contributors'].astype(str).str.split(',')
C:\Users\Youcode\AppData\Local\Temp\ipykernel_31736\3053713290.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  contributions1['contributions_count'] = contributions1['contributions_count'].astype(str).str.split(',')

In [16]:
contributions['contributors'] = contributions['contributors'].str.replace("'", "")
contributions['contributors'] = contributions['contributors'].str.replace("\"", "")
contributions['contributors'] = contributions['contributors'].str.replace("[", "")
contributions['contributors'] = contributions['contributors'].str.replace("]", "")
contributions['contributors'] = contributions['contributors'].str.strip()

contributions['contributions_count'] = contributions['contributions_count'].str.replace("[", "")
contributions['contributions_count'] = contributions['contributions_count'].str.replace("]", "")
contributions['contributions_count'] = contributions['contributions_count'].str.strip()

C:\Users\Youcode\AppData\Local\Temp\ipykernel_31736\3726098073.py:3: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  contributions['contributors'] = contributions['contributors'].str.replace("[", "")
C:\Users\Youcode\AppData\Local\Temp\ipykernel_31736\3726098073.py:4: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  contributions['contributors'] = contributions['contributors'].str.replace("]", "")
C:\Users\Youcode\AppData\Local\Temp\ipykernel_31736\3726098073.py:7: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  contributions['contributions_count'] = contributions['contributions_count'].str.replace("[", "")
C:\Users\Youcode\AppData\Local\Temp\ipykernel_31736\3726098073.py:8: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  contributions['contributions_count'] = contributions['contributions_count'].str.replace("]", "")

In [17]:
contributions

,url,contributors,contributions_count
0,https://github.com/sumn2u/learn-javascript,gnwx,83
0,https://github.com/sumn2u/learn-javascript,sumn2u,64
0,https://github.com/sumn2u/learn-javascript,Anuj-Khadka,2
0,https://github.com/sumn2u/learn-javascript,sahilxkhadka,2
0,https://github.com/sumn2u/learn-javascript,hemants1703,1
...,...,...,...
15486,https://github.com/dabit3/lens-algorithm-playg...,dabit3,12
15486,https://github.com/dabit3/lens-algorithm-playg...,YosephKS,9
15487,https://github.com/dragonked2/Egyscan,dragonked2,38
15488,https://github.com/CNCKitchen/TamaDroppy,CNCKitchen,2
15489,https://github.com/PB2204/Hacking-Animation,PB2204,1

In [18]:
# Insertion des donnÃ©es dans la table "Owner"
contributors_table = contributions[["contributors"]].drop_duplicates().reset_index(drop=True)

contributors_table.insert(0, "id_Contributors", range(1, len(contributors_table) + 1))
#insert_owner_data("Owner", owner_table[["id_owner", "owner"]])
display(contributors_table)

       id_Contributors  contributors
0                    1          gnwx
1                    2        sumn2u
2                    3   Anuj-Khadka
3                    4  sahilxkhadka
4                    5   hemants1703
...                ...           ...
35864            35865      Hacksore
35865            35866      YoavLevi
35866            35867      YosephKS
35867            35868    dragonked2
35868            35869    CNCKitchen

[35869 rows x 2 columns]

In [85]:
# Insertion des donnÃ©es dans la table "Contributors" 

def insert_contributors_data(cursor, contributors_data):
    for index, row in contributors_data.iterrows():
        cursor.execute("INSERT INTO Contributors (id_Contributors, name_Contributors) VALUES (?, ?)", row["id_Contributors"], row["contributors"])
    conn.commit()

    # Appel de la fonction pour insÃ©rer les donnÃ©es dans la table "Contributors"
insert_contributors_data(cursor, contributors_table)

# Fermeture de la connexion Ã  la base de donnÃ©es
conn.close()

In [19]:
merged_df = contributions.merge(repo_table, on='url', how='left')
merged_df1 = merged_df.merge(contributors_table, on='contributors', how='left')
merged_df1 = merged_df1[['id_repo', 'id_Contributors', 'contributions_count']]
merged_df1

       id_repo  id_Contributors contributions_count
0            1                1                  83
1            1                2                  64
2            1                3                   2
3            1                4                   2
4            1                5                   1
...        ...              ...                 ...
46153    15487             4933                  12
46154    15487            35867                   9
46155    15488            35868                  38
46156    15489            35869                   2
46157    15490            32484                   1

[46158 rows x 3 columns]

In [20]:
# Insertion des donnÃ©es dans la table "Contributors_repo" 

def insert_Contributors_repo_data(cursor, contributors_repo_data):
    for index, row in contributors_repo_data.iterrows():
        cursor.execute("INSERT INTO Contributors_repo (id_Contributor, id_Repo, contribution_count) VALUES (?, ?, ?)", row["id_Contributors"], row["id_repo"], row["contributions_count"])
    conn.commit()

    # Appel de la fonction pour insÃ©rer les donnÃ©es dans la table "Contributors"
insert_Contributors_repo_data(cursor, merged_df1)

# Fermeture de la connexion Ã  la base de donnÃ©es
conn.close()